import { ShieldAlert } from "lucide-react";

/**
 * The mistake this exists to prevent:
 *
 * Every signal here is computed from REAL market data. Binary brokers also
 * list "OTC" versions of the same instruments (e.g. "EUR/USD OTC"), which
 * stay open at weekends. Those are synthetic price series generated by the
 * broker, not the real market, and the broker does not publish how they're
 * derived.
 *
 * So placing a signal from this platform on an OTC instrument is not a
 * slightly worse trade — the analysis and the settlement price are unrelated
 * series, while the signal still looks like a confident graded result. The
 * backend refuses OTC symbols outright (apps/api/app/instruments.py); this is
 * the human-facing half of that guard, shown where the mistake would actually
 * be made.
 */
export function OtcWarning() {
  return (
    <div className="flex items-start gap-2.5 rounded-lg border border-put/30 bg-put-muted/40 px-3.5 py-2.5 text-xs text-put-foreground">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-put" />
      <span>
        <strong className="font-semibold">Place these on the real-market instrument only.</strong> These signals are
        computed from real exchange prices. Your broker&apos;s{" "}
        <strong className="font-semibold">&ldquo;OTC&rdquo; weekend pairs are a different, broker-generated price
        series</strong> — a signal from this platform says nothing about them, even though it will still look like a
        valid one. When forex is closed, use the 24/7 crypto pairs instead.
      </span>
    </div>
  );
}
