import { Card, CardContent } from "@/components/ui/card";
import { MarketRead } from "@/components/dashboard/market-read";
import { DirectionBadge } from "@/components/shared/badges";
import { ASSET_CONFIGS, OTC_ASSET_LIST } from "@/data/assets";
import { formatRelative } from "@/lib/utils";
import type { Signal } from "@/types";
import { Radio } from "lucide-react";

/**
 * Broker-generated instruments, in their own section.
 *
 * Kept apart from the real-market grid deliberately, and not merely for
 * layout. Spec section 72: these statistics must never be pooled. A
 * synthetic index and EUR/USD are priced by different things — one by a
 * broker's generator, one by a market — and a result on either says nothing
 * about the other. Rendering them in one grid would put that mistake one
 * glance away, and the totals above would quietly include both.
 */
export function OtcSection({
  signals,
  emptyReason,
}: {
  signals: Record<string, Signal | null>;
  emptyReason?: string | null;
}) {
  const present = OTC_ASSET_LIST.filter((symbol) => signals[symbol]);

  return (
    <section className="space-y-3">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h2 className="text-sm font-semibold text-foreground">
          Broker-generated · Deriv
        </h2>
        <p className="text-xs text-muted-foreground">
          Trades 24/7 — including when forex is closed
        </p>
      </div>

      <div className="flex items-start gap-2.5 rounded-lg border border-border bg-card/40 px-3.5 py-2 text-xs text-muted-foreground">
        <Radio className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
        <span>
          These prices are generated by Deriv, not by any market, and are a
          different series from both the pairs above and from any other broker&apos;s
          &ldquo;OTC&rdquo; instrument of a similar name. Their results are tracked
          separately and are never counted in the figures at the top of this page.
        </span>
      </div>

      {present.length === 0 ? (
        <Card className="border-dashed">
          <CardContent className="space-y-2 p-5 text-sm text-muted-foreground">
            <p>No decision is visible for these instruments yet.</p>
            {emptyReason && <p className="text-foreground">{emptyReason}</p>}
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {present.map((symbol, i) => {
            const signal = signals[symbol]!;
            const cfg = ASSET_CONFIGS[symbol];
            const accent =
              signal.direction === "CALL" ? "bg-call"
              : signal.direction === "PUT" ? "bg-put"
              : "bg-notrade/70";

            return (
              <Card
                key={symbol}
                className="card-premium-hover rise-in overflow-hidden"
                style={{ animationDelay: `${i * 70}ms` }}
              >
                <div className={`h-[2px] w-full ${accent}`} />
                <CardContent className="space-y-3.5 p-5">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="text-sm font-semibold text-foreground">{cfg.displayName}</p>
                      <p className="text-xs text-muted-foreground">{cfg.shortName}</p>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      {formatRelative(signal.lastEvaluatedAt ?? signal.generatedAt)}
                    </p>
                  </div>

                  <DirectionBadge direction={signal.direction} />

                  <p className="text-xs leading-relaxed text-muted-foreground">
                    {signal.warnings[0] ?? signal.reasons[0] ?? "No reason recorded."}
                  </p>

                  <MarketRead signal={signal} />
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </section>
  );
}
