export default function DisclaimerPage() {
  return (
    <div className="container max-w-2xl py-16">
      <h1 className="text-3xl font-semibold text-foreground">Disclaimer</h1>
      <div className="mt-6 space-y-4 text-sm leading-relaxed text-muted-foreground">
        <p>
          NorthFXTrade provides algorithmic market analysis and informational trading signals for XAU/USD, EUR/USD
          and GBP/USD. It does not place trades on your behalf and does not automate any broker or trading platform,
          including Quotex. Every signal is intended for manual review and manual execution only.
        </p>
        <p>
          Trading involves substantial risk of loss and is not suitable for every investor. Historical or simulated
          performance shown anywhere on this platform does not guarantee future results. Past accuracy on resolved
          signals reflects only the specific historical or demo period measured — market conditions change.
        </p>
        <p>
          We do not claim, promise, or imply a guaranteed win rate, "guaranteed profit," or any fixed accuracy figure.
          Confidence percentages and grades are generated by a signal engine with clearly stated methodology, and
          "NO TRADE" is treated as a valid, expected outcome — not a failure of the system.
        </p>
        <p>
          You are solely responsible for your own trading decisions. Consult a licensed financial advisor before
          making decisions based on any signal or analysis provided here.
        </p>
      </div>
    </div>
  );
}
