"""
Instrument registry and feed provenance (spec Phase 2 / Phase 30).

WHAT CHANGED AND WHY
--------------------
This module used to refuse every OTC symbol outright. That was the right
call while no OTC feed existed -- but it was a blunt instrument aimed at
the wrong target.

The actual danger was never the OTC *symbol*. It was analysing a
broker-generated series using a public-market feed: reading real
interbank EUR/USD and emitting a graded signal for "EUR/USD (OTC)", which
is a different series that Quotex generates internally. Those two are
unrelated, and the signal still renders as confident and graded. That is
the most dangerous output this system can produce, because it looks
exactly like a real one.

So the rule is now a provenance check rather than a ban:

    An instrument may only be analysed using a feed of the class that
    actually produces that instrument's prices.

A Quotex OTC instrument therefore becomes legitimate the moment genuine
Quotex OTC prices are what is flowing in -- and stays refused until then.
The check is symmetric: a public-market feed may not serve an OTC
instrument, and an OTC feed may not serve a real-market one.

WHAT THIS MODULE DELIBERATELY DOES NOT DO
-----------------------------------------
It does not obtain broker prices. There is no vendor selling Quotex's
internal series, and the only code that reaches it logs into a user's
account over an undocumented websocket -- which the project spec (section
43) forbids, which handles broker credentials, and which can get the
account closed. This module defines the CONTRACT such a feed must satisfy
so that whatever supplies those prices is used correctly and provably.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum


class MarketType(str, Enum):
    """What kind of thing produces this instrument's prices."""

    FOREX = "FOREX"
    METAL = "METAL"
    CRYPTO = "CRYPTO"
    # A price series generated by a broker's own system rather than by any
    # exchange or interbank market. Not "a less liquid market" -- a
    # different category of object entirely.
    BROKER_OTC = "BROKER_OTC"


class FeedKind(str, Enum):
    """What kind of source a set of candles came from."""

    # Exchange / interbank data vendors: Twelve Data and anything like it.
    PUBLIC_MARKET = "PUBLIC_MARKET"
    # One specific broker's own synthetic series.
    BROKER_OTC = "BROKER_OTC"
    # Deterministic local placeholder data. Never valid for a real signal.
    DEMO = "DEMO"


@dataclass(frozen=True)
class FeedDescriptor:
    """Provenance for a set of candles: who produced them, and of what kind.

    Carried alongside the candles rather than inferred from the symbol,
    because the symbol is exactly what cannot be trusted here -- the whole
    failure mode is a symbol that LOOKS like EUR/USD being priced by
    something that isn't EUR/USD.
    """

    name: str                    # "twelve_data", "quotex_otc", "csv_import", "demo"
    kind: FeedKind
    broker: str | None = None    # required when kind is BROKER_OTC


@dataclass(frozen=True)
class TradingProfile:
    """Which timeframes to analyse, and over what horizons to trade.

    These differ by an order of magnitude between instrument classes, and
    hardcoding one set was what made OTC impossible to express. A real-market
    signal reasons over hours and expires in 15-60 minutes; a Quotex OTC
    signal reasons over minutes and expires in 15-180 SECONDS.

    Held on the instrument rather than passed around, so adding an instrument
    class is a registry entry instead of a branch inside the engine.
    """

    # Slowest to fastest. Spec Phase 4's ladder: the slow end supplies trend
    # context, the fast end supplies the entry trigger.
    timeframes: tuple[str, ...]
    # The timeframe entry_price is read from, and whose staleness is checked.
    # Always the fastest, but named explicitly rather than inferred, because
    # "last element of a tuple" is an easy thing to silently reorder.
    entry_timeframe: str
    # Candidate horizons, in SECONDS. Never minutes: 15 seconds is not an
    # integer number of minutes, and that is exactly what blocked OTC.
    expiries_seconds: tuple[int, ...]
    # How stale the newest entry-timeframe bar may be before the engine
    # refuses to decide. Scaled to the timeframe: 15 minutes of staleness is
    # a minor gap on M5 and an eternity on S15.
    max_data_age_seconds: int

    def __post_init__(self) -> None:
        if self.entry_timeframe != self.timeframes[-1]:
            raise ValueError(
                f"entry_timeframe {self.entry_timeframe!r} must be the fastest timeframe "
                f"(last of {self.timeframes})"
            )
        if not self.expiries_seconds:
            raise ValueError("a profile must offer at least one expiry")


# Real markets: hours of context, expiries of 15/30/60 minutes. Unchanged
# from what the engine has always done -- expressed as data now rather than
# as constants inside the engine.
PUBLIC_MARKET_PROFILE = TradingProfile(
    timeframes=("H4", "H1", "M15", "M5"),
    entry_timeframe="M5",
    expiries_seconds=(900, 1800, 3600),
    max_data_age_seconds=900,  # three closed M5 bars
)

# Broker OTC: minutes of context, expiries of seconds. The ladder follows
# spec Phase 4 -- M5 for trend context, M1 for structure and momentum,
# S30/S15 for the entry trigger.
#
# A 15-second expiry on a 15-second entry bar is included but is the most
# noise-dominated horizon on offer: entry is the close of one bar and
# settlement the close of the next, so no confirmation is possible in
# between. It is a candidate, not a recommendation, and the strategy config
# can disable it per instrument.
# Retargeted to a 5-minute primary expiry, and to timeframes a real feed
# can actually supply.
#
# The previous ladder ran M5/M1/S30/S15 with 15-180s expiries, written
# against a hypothetical tick feed. Deriv's finest CANDLE is 60 seconds, so
# S15 and S30 have to be built from its tick stream
# (deriv_feed.ticks_to_candles). That pipeline is worth having and is not
# built yet, and shipping a profile whose entry timeframe cannot be filled
# would mean an engine that refuses every cycle on missing history and
# looks broken rather than unfinished.
#
# So the ladder is M15 context down to M1 entry, all directly available,
# with 300s as the primary horizon. Adding S30 and S15 back is a change to
# these two tuples once ticks are being collected -- nothing downstream
# depends on the names.
OTC_PROFILE = TradingProfile(
    timeframes=("M15", "M5", "M3", "M1"),
    entry_timeframe="M1",
    expiries_seconds=(60, 180, 300, 600),
    max_data_age_seconds=180,  # three closed M1 bars
)


@dataclass(frozen=True)
class Instrument:
    symbol: str                  # canonical internal id, e.g. "EURUSD_OTC"
    display_name: str            # "EUR/USD (OTC)"
    market_type: MarketType
    # The broker whose system generates this instrument. None for real
    # markets -- nobody "owns" EUR/USD.
    broker: str | None = None
    # True for markets with no weekly close. Note that OTC instruments are
    # continuously available too, but for a different reason: the generator
    # simply never stops. That distinction matters enough to keep the flag
    # separate from market_type.
    trades_continuously: bool = False

    @property
    def is_otc(self) -> bool:
        return self.market_type is MarketType.BROKER_OTC

    @property
    def required_feed_kind(self) -> FeedKind:
        return FeedKind.BROKER_OTC if self.is_otc else FeedKind.PUBLIC_MARKET

    @property
    def profile(self) -> TradingProfile:
        return OTC_PROFILE if self.is_otc else PUBLIC_MARKET_PROFILE


# ---------------------------------------------------------------------------
# The registry
# ---------------------------------------------------------------------------
# One place, so nothing anywhere else has to guess what a symbol means.
# Phase 30: start narrow. One OTC instrument until it has a sample size
# worth trusting -- five pairs each reach a conclusion five times slower,
# and "no pair ever reached significance" is the usual result of widening
# early.

REGISTRY: dict[str, Instrument] = {
    "XAUUSD": Instrument("XAUUSD", "XAU/USD", MarketType.METAL),
    "EURUSD": Instrument("EURUSD", "EUR/USD", MarketType.FOREX),
    "GBPUSD": Instrument("GBPUSD", "GBP/USD", MarketType.FOREX),
    "BTCUSD": Instrument("BTCUSD", "BTC/USD", MarketType.CRYPTO, trades_continuously=True),
    "ETHUSD": Instrument("ETHUSD", "ETH/USD", MarketType.CRYPTO, trades_continuously=True),
    # Kept, and kept unreachable. Quotex publishes no market-data API, so
    # nothing can legitimately price this. It stays in the registry so the
    # provenance check has something to refuse rather than an unknown
    # symbol, and so the reason is recorded where someone will find it.
    "EURUSD_OTC": Instrument(
        "EURUSD_OTC",
        "EUR/USD (OTC)",
        MarketType.BROKER_OTC,
        broker="QUOTEX",
        trades_continuously=True,
    ),

    # Deriv synthetic indices: broker-generated, 24/7, and available through
    # a documented public API that needs no account credentials.
    #
    # The number in each name is that index's nominal annualised volatility,
    # which is the whole basis for choosing between them: V25 and V100 are
    # the same generator at very different speeds, so a strategy tuned on one
    # has no claim on the other. They are separate instruments here for the
    # same reason XAUUSD and EURUSD are.
    "DERIV_V25": Instrument(
        "DERIV_V25", "Volatility 25", MarketType.BROKER_OTC,
        broker="DERIV", trades_continuously=True,
    ),
    "DERIV_V50": Instrument(
        "DERIV_V50", "Volatility 50", MarketType.BROKER_OTC,
        broker="DERIV", trades_continuously=True,
    ),
    "DERIV_V75": Instrument(
        "DERIV_V75", "Volatility 75", MarketType.BROKER_OTC,
        broker="DERIV", trades_continuously=True,
    ),
}

# Our registry symbol to the code Deriv's API expects. Kept as an explicit
# map rather than a string transformation: a rule that happens to work for
# today's three names would silently mis-address the first instrument that
# does not fit the pattern, and mis-addressing an instrument is how a
# strategy ends up validated against the wrong series.
DERIV_API_SYMBOLS: dict[str, str] = {
    "DERIV_V25": "R_25",
    "DERIV_V50": "R_50",
    "DERIV_V75": "R_75",
}


def deriv_api_symbol(symbol: str) -> str:
    try:
        return DERIV_API_SYMBOLS[symbol]
    except KeyError:
        raise KeyError(
            f"{symbol!r} is not a Deriv instrument. Add it to DERIV_API_SYMBOLS "
            "with the code Deriv's API uses, and to REGISTRY with broker='DERIV'."
        ) from None


class UnknownInstrumentError(KeyError):
    """Raised for a symbol not in the registry. Unregistered symbols are
    refused rather than guessed at: guessing is how an OTC instrument gets
    silently treated as a real one."""


class FeedProvenanceError(ValueError):
    """Raised when a feed is used for an instrument it cannot price."""


def get_instrument(symbol: str) -> Instrument:
    try:
        return REGISTRY[str(symbol).upper()]
    except KeyError as exc:
        raise UnknownInstrumentError(
            f"{symbol!r} is not in the instrument registry. Add it to "
            "app/instruments.py with an explicit market_type — an unregistered "
            "symbol is refused rather than assumed to be a real market."
        ) from exc


# ---------------------------------------------------------------------------
# Synthetic-symbol detection (still needed, for a narrower job)
# ---------------------------------------------------------------------------
# Catches an OTC-looking symbol that was never registered. Without this, a
# typo'd or newly-added "EURUSD-OTC" would fall through as an unknown symbol
# and someone would "fix" it by registering it as FOREX.
_OTC_PATTERNS = (
    re.compile(r"\bOTC\b", re.IGNORECASE),
    re.compile(r"[-_ ]OTC", re.IGNORECASE),
    re.compile(r"\bSYNTHETIC\b", re.IGNORECASE),
    re.compile(r"\bVOLATILITY\s*\d+", re.IGNORECASE),
    re.compile(r"\bBOOM\s*\d+|\bCRASH\s*\d+", re.IGNORECASE),
)


def looks_synthetic(symbol: str) -> bool:
    if not symbol:
        return False
    return any(p.search(symbol) for p in _OTC_PATTERNS)


# ---------------------------------------------------------------------------
# The provenance check -- the point of this whole module
# ---------------------------------------------------------------------------

def assert_feed_matches_instrument(symbol: str, feed: FeedDescriptor | None) -> Instrument:
    """Raises unless `feed` can legitimately price `symbol`. Returns the
    resolved Instrument so callers get the registry lookup for free.

    Raises rather than returning a flag, for the same reason as before: a
    caller that forgets to check a boolean fails open, and failing open
    here means a confident signal about a price series the user is not
    trading.

    `feed=None` means "provenance not stated". That is tolerated for real
    markets, where it preserves the behaviour of every existing caller and
    where the historical risk was low. It is REFUSED for OTC instruments,
    which are fail-closed by design: OTC analysis has to prove where its
    prices came from, because that is the only thing separating a real OTC
    signal from the dangerous fiction this module exists to prevent.
    """
    instrument = get_instrument(symbol)

    if feed is None:
        if instrument.is_otc:
            raise FeedProvenanceError(
                f"{symbol!r} is a broker-OTC instrument and requires an explicit feed "
                "descriptor. Its prices are generated by the broker, so analysis is only "
                "meaningful when the candles provably came from that broker's own OTC feed."
            )
        return instrument

    if feed.kind is FeedKind.DEMO:
        raise FeedProvenanceError(
            f"Refusing to analyse {symbol!r} from the demo feed. Demo candles are "
            "deterministic placeholders, not market prices — a signal derived from them "
            "would be fiction rendered as a graded result."
        )

    if feed.kind is not instrument.required_feed_kind:
        raise FeedProvenanceError(
            f"Feed {feed.name!r} is {feed.kind.value}, but {symbol!r} is "
            f"{instrument.market_type.value} and can only be priced by "
            f"{instrument.required_feed_kind.value}. "
            + (
                "A public-market feed does NOT price a broker's OTC series: they are "
                "unrelated series that happen to share a name."
                if instrument.is_otc
                else "A broker's OTC series does NOT price the real market."
            )
        )

    if instrument.is_otc and feed.broker != instrument.broker:
        raise FeedProvenanceError(
            f"{symbol!r} is generated by {instrument.broker}, but these candles came from "
            f"{feed.broker!r}. One broker's synthetic series does not price another's."
        )

    return instrument


# ---------------------------------------------------------------------------
# Back-compat + convenience
# ---------------------------------------------------------------------------

CRYPTO_SYMBOLS: frozenset[str] = frozenset(
    s for s, i in REGISTRY.items() if i.market_type is MarketType.CRYPTO
)


def is_crypto_symbol(symbol: str) -> bool:
    return str(symbol).upper() in CRYPTO_SYMBOLS


def is_otc_symbol(symbol: str) -> bool:
    sym = str(symbol).upper()
    known = REGISTRY.get(sym)
    return known.is_otc if known else looks_synthetic(sym)


def trades_continuously(symbol: str) -> bool:
    """True for markets with no weekly close: crypto, and OTC instruments
    (whose generator simply never stops)."""
    known = REGISTRY.get(str(symbol).upper())
    return bool(known and known.trades_continuously)
