"""
Deriv synthetic indices: a broker-generated price series with an official API.

WHY THIS EXISTS
---------------
The platform needed a market that trades when forex does not, and whose
prices are generated by a broker rather than an exchange -- the class of
instrument Quotex calls "OTC". Quotex publishes no market-data API, and
every client that exists authenticates as the account holder, which the
project spec forbids and which puts the account at risk.

Deriv publishes the same class of instrument through a documented public
WebSocket API. No credentials are needed for market data, the schema is
versioned, and closed candles are not revised. That makes it a source the
provenance rules can actually vouch for.

WHAT IT IS NOT
--------------
These are NOT Quotex OTC prices, and a signal computed here says nothing
about a Quotex instrument of a similar name. Both are broker-generated,
by different brokers, from different generators. The instrument registry
records the broker for exactly this reason, and the feed-kind check
refuses to price one broker's instrument with another's feed.

THE PROPERTY NO ENGINEERING REMOVES
-----------------------------------
The firm generating these prices is the firm paying the winning trades,
and the generator can change without notice. A backtested edge on such a
series carries no guarantee of persisting. That is not an argument against
building this -- it is why the shadow-mode and calibration machinery
matters more here than it would on a real market, and why
`history_is_stable` is part of the feed contract rather than an assumption.
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime, timezone

from app.market_data.errors import MarketDataError
from app.market_data.otc import OTCBar, OTCFeed

logger = logging.getLogger(__name__)

ENDPOINT = "wss://ws.derivws.com/websockets/v3"

# The only granularities the API accepts, in seconds. Anything finer has to
# be built from the tick stream -- see ticks_to_candles() below.
SUPPORTED_GRANULARITY = (60, 120, 180, 300, 600, 900, 1800, 3600, 7200, 14400, 28800, 86400)

# Our timeframe names to Deriv granularity.
TIMEFRAME_GRANULARITY: dict[str, int] = {
    "M1": 60,
    "M3": 180,
    "M5": 300,
    "M15": 900,
    "H1": 3600,
    "H4": 14400,
}

# Deriv caps a single ticks_history response.
MAX_COUNT = 5000


class DerivError(MarketDataError):
    """The API answered, and said no. Carries Deriv's own error code so a
    quota refusal and a bad symbol are distinguishable without string
    matching."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(f"Deriv API error [{code}]: {message}")
        self.code = code


class DerivSyntheticFeed(OTCFeed):
    name = "deriv_synthetic"
    broker = "DERIV"
    # Deriv does not revise a candle once it has closed. Asserted here
    # rather than assumed silently -- the backtester's validity depends on
    # it, and a source that replayed history would have to say so.
    history_is_stable = True

    def __init__(self, app_id: str, *, timeout_seconds: float = 20.0) -> None:
        if not app_id:
            raise ValueError(
                "Deriv requires an app_id even for public market data. "
                "Register an APPLICATION at https://api.deriv.com and set DERIV_APP_ID."
            )
        # An app_id is a small integer that identifies the application. An
        # API TOKEN is a long secret that authorises actions on an ACCOUNT,
        # and Deriv's token page is the easier of the two to find -- so
        # pasting one here is the obvious mistake, and it must not be a
        # quiet one.
        #
        # It matters more than a wrong-value error usually would. A token
        # can carry the `trade` scope, and this platform's central promise
        # is that it never places a trade. A trading credential sitting in
        # its configuration is one careless commit away from the
        # auto-execution path the spec forbids -- so refuse it at the door,
        # rather than letting it sit unused and available.
        text = str(app_id).strip()
        if not text.isdigit():
            raise ValueError(
                f"DERIV_APP_ID must be the numeric app id, not {'a token' if len(text) > 12 else 'this'}. "
                "Market data needs NO account token — if what you have is a long "
                "secret from the API-token page, delete it (especially if it has the "
                "Trade scope) and register an application instead, which yields a number."
            )
        self.app_id = text
        self.timeout_seconds = timeout_seconds

    def _now(self) -> datetime:
        """Overridable so the closed-bar rule can be tested against a fixed
        clock. Whether a bar has closed is the most important decision in
        this file, and a rule that can only be exercised against the wall
        clock is a rule that is checked by luck."""
        return datetime.now(timezone.utc)

    @property
    def url(self) -> str:
        return f"{ENDPOINT}?app_id={self.app_id}"

    # -- transport ---------------------------------------------------------

    async def _request(self, payload: dict) -> dict:
        """One request, one response, one connection.

        Deliberately not a long-lived socket. The collector polls on a
        schedule measured in minutes; holding a connection open between
        polls buys nothing and adds a reconnection state machine, silent
        staleness, and a second thing that can be quietly dead. When this
        engine moves to tick streaming, that will be a separate object with
        its own lifecycle rather than this one grown a heartbeat.
        """
        try:
            from websockets.asyncio.client import connect
        except ImportError:  # pragma: no cover -- older websockets releases
            from websockets.client import connect  # type: ignore[no-redef]

        try:
            async with asyncio.timeout(self.timeout_seconds):
                async with connect(self.url) as socket:
                    await socket.send(json.dumps(payload))
                    while True:
                        raw = await socket.recv()
                        message = json.loads(raw)
                        # The socket also carries unsolicited traffic (ping,
                        # subscription updates). Matching on msg_type rather
                        # than taking the first frame stops an unrelated
                        # message being parsed as our answer.
                        if "error" in message:
                            err = message["error"]
                            raise DerivError(err.get("code", "unknown"), err.get("message", ""))
                        if message.get("msg_type") in ("candles", "history"):
                            return message
        except DerivError:
            raise
        except asyncio.TimeoutError as exc:
            raise MarketDataError(
                f"Deriv did not answer within {self.timeout_seconds}s"
            ) from exc
        except Exception as exc:  # noqa: BLE001
            # Always name the class: str() on several websocket and asyncio
            # errors is empty, which produced log lines that ended in a colon.
            raise MarketDataError(
                f"Deriv request failed: {type(exc).__name__}: {exc}"
            ) from exc

    # -- the OTCFeed contract ---------------------------------------------

    async def fetch_bars(self, symbol: str, timeframe: str, count: int) -> list[OTCBar]:
        granularity = TIMEFRAME_GRANULARITY.get(timeframe)
        if granularity is None:
            raise MarketDataError(
                f"Deriv has no {timeframe} candles — its finest granularity is 60s. "
                "Sub-minute bars must be built from the tick stream; see ticks_to_candles()."
            )

        # One extra, because the newest candle returned is still forming and
        # is dropped below. Asking for exactly `count` would quietly return
        # one fewer closed bar than the caller asked for.
        wanted = min(MAX_COUNT, max(1, count) + 1)
        message = await self._request({
            "ticks_history": symbol,
            "end": "latest",
            "count": wanted,
            "style": "candles",
            "granularity": granularity,
            "adjust_start_time": 1,
        })

        raw_candles = message.get("candles") or []
        now = self._now()
        bars: list[OTCBar] = []

        for candle in raw_candles:
            open_time = datetime.fromtimestamp(int(candle["epoch"]), tz=timezone.utc)
            # A candle whose period has not elapsed is still moving. Including
            # it corrupts every indicator and makes a backtest better informed
            # than live was -- the single most important rule in this file.
            if (now - open_time).total_seconds() < granularity:
                continue
            bars.append(OTCBar(
                symbol=symbol,
                timeframe=timeframe,
                open_time=open_time,
                open=float(candle["open"]),
                high=float(candle["high"]),
                low=float(candle["low"]),
                close=float(candle["close"]),
                is_closed=True,
                source=self.name,
            ))

        if not bars:
            raise MarketDataError(
                f"Deriv returned no CLOSED {timeframe} candles for {symbol!r} "
                f"({len(raw_candles)} received, all still forming)."
            )

        bars.sort(key=lambda b: b.open_time)
        return bars[-count:]

    async def fetch_ticks(self, symbol: str, count: int = 5000) -> list[tuple[datetime, float]]:
        """Raw ticks, oldest first — the input for sub-minute candles."""
        message = await self._request({
            "ticks_history": symbol,
            "end": "latest",
            "count": min(MAX_COUNT, max(1, count)),
            "style": "ticks",
        })
        history = message.get("history") or {}
        times = history.get("times") or []
        prices = history.get("prices") or []
        if not times or len(times) != len(prices):
            raise MarketDataError(
                f"Deriv tick history for {symbol!r} came back malformed: "
                f"{len(times)} timestamps against {len(prices)} prices."
            )
        return [
            (datetime.fromtimestamp(int(t), tz=timezone.utc), float(p))
            for t, p in zip(times, prices)
        ]


def ticks_to_candles(
    ticks: list[tuple[datetime, float]],
    seconds: int,
    *,
    now: datetime | None = None,
) -> list[dict]:
    """Build OHLC bars of `seconds` from ticks, returning CLOSED bars only.

    Deriv's finest candle is 60 seconds, and this engine's OTC profile wants
    15 and 30. Those have to be built here, from the ticks the same API
    provides -- which is also the honest way round: a 15-second bar derived
    from real ticks is real, whereas one interpolated from a minute bar
    would be invented.

    Buckets are aligned to absolute epoch boundaries, not to the first tick
    seen, so the same bar has the same open_time on every run. Aligning to
    arrival time would make history depend on when the collector happened
    to start, and no two runs would agree.
    """
    if seconds <= 0:
        raise ValueError("seconds must be positive")
    if not ticks:
        return []

    now = now or datetime.now(timezone.utc)
    buckets: dict[int, list[float]] = {}
    for at, price in sorted(ticks, key=lambda t: t[0]):
        start = int(at.timestamp()) // seconds * seconds
        buckets.setdefault(start, []).append(price)

    cutoff = int(now.timestamp())
    out: list[dict] = []
    for start in sorted(buckets):
        if start + seconds > cutoff:
            continue  # still forming
        prices = buckets[start]
        out.append({
            "open_time": datetime.fromtimestamp(start, tz=timezone.utc),
            "open": prices[0],
            "high": max(prices),
            "low": min(prices),
            "close": prices[-1],
            "tick_count": len(prices),
        })
    return out
