-- ============================================================================
-- 20260903000024_seed_deriv_instruments.sql
--
-- The three Deriv synthetic indices, as collectable instruments.
--
-- Mirrors app/instruments.py. Both exist because they answer to different
-- readers -- the engine reads the registry, PostgREST and the frontend read
-- this table -- and a symbol present in one but not the other is a runtime
-- failure rather than a mismatch anyone notices.
--
-- Seeded ACTIVE, unlike the Quotex row (migration 16), because these can
-- actually be priced. Setting a symbol active while nothing can price it is
-- how an instrument ends up looking broken rather than unavailable.
--
-- The number in each name is that index's nominal annualised volatility.
-- V25 and V75 are the same generator at very different speeds, so they are
-- separate instruments for the same reason XAUUSD and EURUSD are: a
-- strategy tuned on one has no claim on the other, and pooling their
-- results would credit an edge to a series that never produced it.
-- ============================================================================

insert into assets (symbol, display_name, short_name, pip_decimal, market_type, broker, trades_continuously, metadata, is_active)
values
  ('DERIV_V25', 'Volatility 25', 'V25', 4, 'BROKER_OTC', 'DERIV', true, '{}'::jsonb, true),
  ('DERIV_V50', 'Volatility 50', 'V50', 4, 'BROKER_OTC', 'DERIV', true, '{}'::jsonb, true),
  ('DERIV_V75', 'Volatility 75', 'V75', 4, 'BROKER_OTC', 'DERIV', true, '{}'::jsonb, true)
on conflict (symbol) do update
  set display_name        = excluded.display_name,
      market_type         = excluded.market_type,
      broker              = excluded.broker,
      trades_continuously = excluded.trades_continuously,
      is_active           = excluded.is_active;

comment on table assets is
  'Configured instruments. market_type BROKER_OTC means the prices are generated by the named broker rather than by any market, and may only ever be priced by that broker''s own feed — see signals.data_source and candles.feed_kind.';
