-- ============================================================================
-- 20260830000016_otc_instruments_and_provenance.sql
--
-- Broker-OTC support, and the data provenance that makes it safe.
--
-- WHAT AN OTC INSTRUMENT IS
-- -------------------------
-- "EUR/USD (OTC)" on Quotex is not EUR/USD. It is a price series Quotex
-- generates internally from historical data, volatility estimates and
-- platform-wide activity. It does not come from any exchange, it is not
-- tied to trading sessions, and economic releases do not move it.
--
-- So it is not a less liquid version of a real pair. It is a different
-- category of object that happens to share a name -- and that shared name
-- is precisely the hazard. Analysing real interbank EUR/USD and shipping
-- the result as a graded signal for EUR/USD OTC produces something
-- indistinguishable from a real signal and completely meaningless.
--
-- THE FIX IS PROVENANCE, NOT PROHIBITION
-- --------------------------------------
-- Every candle and every signal now records the feed that produced it, and
-- the engine refuses any instrument/feed pair that doesn't match. An OTC
-- instrument becomes analysable the moment genuine OTC prices are what is
-- flowing in -- and stays refused until then, by construction rather than
-- by anyone remembering to check.
--
-- BEHAVIOURAL IMPACT: none until an OTC feed is connected. The instrument
-- is seeded inactive, and no OTC data source exists yet.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Instrument classification
-- ---------------------------------------------------------------------------
alter table assets
  -- FOREX | METAL | CRYPTO | BROKER_OTC. Mirrors app/instruments.py's
  -- MarketType; the application registry stays the source of truth for
  -- behaviour, this column exists so SQL and the admin UI can tell the
  -- categories apart without re-deriving them from the symbol.
  add column if not exists market_type text not null default 'FOREX'
    check (market_type in ('FOREX', 'METAL', 'CRYPTO', 'BROKER_OTC')),

  -- Which broker generates this instrument. Null for real markets: nobody
  -- owns EUR/USD. Required for OTC, enforced below -- an OTC row with no
  -- broker could be matched by any broker's feed, defeating the check.
  add column if not exists broker text,

  -- True for markets with no weekly close. Crypto, because the market never
  -- shuts; OTC, because the generator never stops. Same flag, different
  -- reasons, both meaning "do not skip polling at the weekend".
  add column if not exists trades_continuously boolean not null default false;

update assets set market_type = 'METAL'  where symbol = 'XAUUSD';
update assets set market_type = 'CRYPTO', trades_continuously = true
  where symbol in ('BTCUSD', 'ETHUSD');

alter table assets
  drop constraint if exists assets_otc_requires_broker;
alter table assets
  add constraint assets_otc_requires_broker check (
    (market_type = 'BROKER_OTC' and broker is not null)
    or (market_type <> 'BROKER_OTC' and broker is null)
  );

comment on column assets.market_type is
  'BROKER_OTC instruments are generated by a broker, not by any market. They may only be priced by that broker''s own feed — see signals.data_source.';

-- ---------------------------------------------------------------------------
-- Provenance on the data itself
-- ---------------------------------------------------------------------------
-- `candles.source` already records the provider name. `feed_kind` records
-- the CLASS of feed, which is what the safety rule actually turns on: the
-- danger is not "which vendor" but "public market vs broker-generated".
alter table candles
  add column if not exists feed_kind text
    check (feed_kind in ('PUBLIC_MARKET', 'BROKER_OTC', 'DEMO'));

comment on column candles.feed_kind is
  'Class of feed that produced this bar. A BROKER_OTC instrument must never hold PUBLIC_MARKET candles, or vice versa.';

alter table signals
  -- Stamped from the decision. Spec Phase 2/18: a signal must be scored
  -- against the same series it was generated from, and that is only checkable
  -- if the series is recorded on the signal itself.
  add column if not exists data_source text,
  add column if not exists market_type text
    check (market_type in ('FOREX', 'METAL', 'CRYPTO', 'BROKER_OTC'));

comment on column signals.data_source is
  'The feed that priced the candles behind this signal. Resolution must use the same source — scoring a signal against a different feed than generated it produces a number that means nothing.';

-- ---------------------------------------------------------------------------
-- Sub-minute timeframes
-- ---------------------------------------------------------------------------
-- OTC is traded on 15s-1m horizons. The existing check constraint permits
-- only M5/M15/H1/H4, so an OTC bar could not be stored at all.
--
-- Public-market vendors do not sell sub-minute data (Twelve Data's floor is
-- 1min), so in practice these values only ever arrive from an OTC or
-- tick-level feed.
--
-- `timeframe` is the ENUM timeframe_type, not a checked text column, so the
-- values are added to the type. Each ADD VALUE is IF NOT EXISTS so this
-- migration stays re-runnable.
--
-- Ordering note: BEFORE 'M5' keeps the enum's declaration order equal to
-- ascending duration. Postgres sorts enums by declaration order, so an
-- appended 'S15' would sort AFTER 'H4' and quietly break any query that
-- orders by timeframe.
alter type timeframe_type add value if not exists 'S15' before 'M5';
alter type timeframe_type add value if not exists 'S30' before 'M5';
alter type timeframe_type add value if not exists 'M1'  before 'M5';
alter type timeframe_type add value if not exists 'M3'  before 'M5';

-- NOTE: in PostgreSQL a new enum value cannot be used in the SAME
-- transaction that adds it. Supabase's SQL editor runs a statement batch as
-- one transaction, so run this migration on its own and let it commit before
-- anything inserts an S15/S30/M1/M3 candle. Nothing does today -- no OTC feed
-- exists -- but the collector must not be started mid-migration.

-- ---------------------------------------------------------------------------
-- Expiries
-- ---------------------------------------------------------------------------
-- Existing constraint allows only 15/30/60 MINUTES. OTC expiries are 15-180
-- SECONDS, which the column cannot express. Adding a unit column rather than
-- overloading the existing one: silently reinterpreting stored 15s as 15
-- minutes would mis-resolve every historical signal.
alter table signals
  add column if not exists expiry_seconds integer
    check (expiry_seconds is null or expiry_seconds between 5 and 14400);

comment on column signals.expiry_seconds is
  'Expiry in seconds, for sub-minute (OTC) horizons. expiry_minutes stays authoritative for real-market signals; exactly one of the two is set.';

-- ---------------------------------------------------------------------------
-- Seed: one OTC instrument, inactive
-- ---------------------------------------------------------------------------
-- Phase 30: start with one. Widening early means every pair reaches
-- significance slower and none reaches it at all.
--
-- is_active = false ON PURPOSE. No OTC price source exists yet, and an
-- active instrument with no feed would present as "no signals yet" —
-- indistinguishable from a working system in a quiet market. Flip this to
-- true in the same change that connects a conforming feed, never before.
insert into assets (symbol, display_name, short_name, pip_decimal, market_type, broker, trades_continuously, config, is_active)
values ('EURUSD_OTC', 'EUR/USD (OTC)', 'Euro OTC', 5, 'BROKER_OTC', 'QUOTEX', true, '{}'::jsonb, false)
on conflict (symbol) do nothing;
