-- ============================================================================
-- 20260830000011_seed_crypto_assets.sql
--
-- Adds BTC/USD and ETH/USD.
--
-- Why: forex and gold are closed from roughly Friday 22:00 UTC to Sunday
-- 21:00 UTC, which leaves the platform with nothing real to analyse all
-- weekend. Crypto trades continuously on real exchanges, so it gives
-- genuine 24/7 coverage using the same real-market-data pipeline.
--
-- What this deliberately does NOT do: add the broker's weekend "OTC"
-- instruments. Those are synthetic series generated by the broker, not
-- real markets, so this platform's analysis of real prices says nothing
-- about them. See apps/api/app/instruments.py — such symbols are refused
-- outright rather than analysed.
-- ============================================================================

insert into assets (symbol, display_name, short_name, pip_decimal, config, is_active)
values
  ('BTCUSD', 'BTC/USD', 'Bitcoin', 2, '{"market": "crypto", "trades_247": true}'::jsonb, true),
  ('ETHUSD', 'ETH/USD', 'Ethereum', 2, '{"market": "crypto", "trades_247": true}'::jsonb, true)
on conflict (symbol) do nothing;
