"""
Prove the Deriv feed against the live API before trusting anything built on it.

Spec section 68's milestone, in the form this project can actually satisfy:
receive one genuine instrument, construct valid candles, display them, and
be able to compare them against what the broker shows. Run this first; a
strategy measured on a feed nobody verified is measuring the feed.

    set DERIV_APP_ID=your_id
    .venv\\Scripts\\python.exe deriv_check.py
    .venv\\Scripts\\python.exe deriv_check.py --symbol DERIV_V25 --timeframe M5
"""
from __future__ import annotations

import argparse
import asyncio
import sys
from datetime import timezone

from app.config import get_settings
from app.instruments import deriv_api_symbol, get_instrument
from app.market_data.deriv_feed import DerivSyntheticFeed, ticks_to_candles

OK, BAD, INFO = "  OK ", " STOP", "     "


def line(tag: str, text: str) -> None:
    print(f"[{tag}] {text}")


async def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--symbol", default="DERIV_V75")
    parser.add_argument("--timeframe", default="M1")
    parser.add_argument("--count", type=int, default=10)
    args = parser.parse_args()

    settings = get_settings()
    if not settings.deriv_app_id:
        line(BAD, "DERIV_APP_ID is not set. Register a free app id at https://api.deriv.com")
        line(INFO, "then add it to apps/api/.env as DERIV_APP_ID=12345")
        return 1

    try:
        instrument = get_instrument(args.symbol)
        api_symbol = deriv_api_symbol(args.symbol)
    except Exception as exc:  # noqa: BLE001
        line(BAD, f"{args.symbol}: {exc}")
        return 1

    line(OK, f"{instrument.symbol} — {instrument.display_name}, generated by {instrument.broker}")
    line(INFO, f"Deriv calls it {api_symbol}; profile ladder {instrument.profile.timeframes}")

    feed = DerivSyntheticFeed(settings.deriv_app_id)

    print("\n--- candles ---")
    try:
        bars = await feed.fetch_bars(api_symbol, args.timeframe, args.count)
    except Exception as exc:  # noqa: BLE001
        line(BAD, f"{type(exc).__name__}: {exc}")
        return 1

    line(OK, f"{len(bars)} closed {args.timeframe} bars")
    for bar in bars[-5:]:
        print(f"      {bar.open_time.astimezone(timezone.utc):%Y-%m-%d %H:%M:%S}  "
              f"O {bar.open:<12.5f} H {bar.high:<12.5f} L {bar.low:<12.5f} C {bar.close:<12.5f}")

    # Two things worth checking that a glance at the numbers will not catch.
    gaps = [
        (b.open_time - a.open_time).total_seconds()
        for a, b in zip(bars, bars[1:])
    ]
    if gaps and len(set(gaps)) > 1:
        line(BAD, f"uneven spacing between bars: {sorted(set(gaps))} — expected one interval")
    elif gaps:
        line(OK, f"evenly spaced, {gaps[0]:.0f}s apart")

    if any(b.high < b.low for b in bars):
        line(BAD, "a bar has high below low")
    else:
        line(OK, "every bar's OHLC is internally consistent")

    print("\n--- ticks ---")
    try:
        ticks = await feed.fetch_ticks(api_symbol, count=600)
        line(OK, f"{len(ticks)} ticks, newest {ticks[-1][0]:%H:%M:%S} at {ticks[-1][1]}")
        for seconds in (15, 30):
            built = ticks_to_candles(ticks, seconds)
            line(OK 
                 if built else INFO,
                 f"{len(built)} closed {seconds}s bars built from those ticks"
                 + (f", newest {built[-1]['open_time']:%H:%M:%S}" if built else ""))
    except Exception as exc:  # noqa: BLE001
        line(BAD, f"ticks unavailable: {type(exc).__name__}: {exc}")

    print("""
NEXT: compare a few of the candle rows above against the same instrument on
Deriv's own chart. If the times and prices line up, the feed is trustworthy
and the OTC pipeline can be switched on. If they do not, stop -- no strategy
result computed on a mismatched series means anything (spec section 68).
""")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
