@echo off
setlocal
REM ===========================================================================
REM Starts the collector automatically at every logon. Run this ONCE.
REM
REM Uses the per-user Startup folder rather than a scheduled task. schtasks
REM with /sc onlogon requires administrator rights -- it fails with "Access is
REM denied" on a normal account. The Startup folder needs no elevation and
REM touches nothing outside this user profile.
REM
REM What this covers:  closing the window, logging out, restarting the PC,
REM                    and the collector crashing (the wrapper restarts it).
REM What it does NOT:   the machine sleeping. A laptop that sleeps stops
REM                    collecting, and no local setup can change that.
REM ===========================================================================
cd /d "%~dp0"

set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "LAUNCHER=%STARTUP%\NorthFXTrade Collector.bat"

if not exist "%~dp0run-collector-forever.bat" (
  echo Cannot find run-collector-forever.bat next to this script.
  pause
  exit /b 1
)

if not exist "%STARTUP%" (
  echo Could not find the Startup folder:
  echo   %STARTUP%
  pause
  exit /b 1
)

REM Written line by line rather than as one nested command. "start ... cmd /c
REM \"path with spaces\"" stacks three levels of quoting and is a well-known way
REM to produce a launcher that silently does nothing.
> "%LAUNCHER%" echo @echo off
>> "%LAUNCHER%" echo REM Auto-generated by install-autostart.bat.
>> "%LAUNCHER%" echo REM Delete this file to stop the collector starting at logon.
>> "%LAUNCHER%" echo title NorthFXTrade Collector
REM No "cd /d" line: %~dp0 ends in a backslash, so "...\api\" puts \" at the
REM end of the argument, which batch can read as an escaped quote. The wrapper
REM anchors itself with its own cd /d anyway, so the line is redundant risk.
>> "%LAUNCHER%" echo call "%~dp0run-collector-forever.bat"

if not exist "%LAUNCHER%" (
  echo Could not write the startup launcher.
  pause
  exit /b 1
)

echo.
echo Installed. The collector will start at every logon, minimised, and
echo restart itself if it crashes.
echo.
echo   Launcher: %LAUNCHER%
echo   Logs:     %~dp0logs\collector.log
echo.
echo To start it right now without logging out, run:
echo   start-collector.bat        (foreground, this window)
echo   run-collector-forever.bat  (foreground, auto-restarts)
echo.
echo To remove autostart later, delete the Launcher file above,
echo or run uninstall-autostart.bat
echo.
echo REMINDER: this does not stop the machine sleeping. A laptop that sleeps
echo still stops collecting candles and resolving signals.
echo.
pause
